
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="header__logo">
		 <a  href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
		<img width="150" src="//www.kidcitystores.com/pub/media/logo/default/KidsCity_Logo_1_3.jpg"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
            
        />
		</a>
</div>