<div id="footer-social">
	<div class="f-left">&copy <?= date('Y') ?> Kid City, Inc. All Rights Reserved</div>
	<div class="f-right">
		<!--<a class="facebook-logo" href="https://www.facebook.com/kidcitystores" target="_blank"></a>-->
		<a href="https://www.facebook.com/kidcitystores" target="_blank"><i class="icon-facebook-with-circle" style="color: gray;    font-size: 29px;"></i></a>
		<a href="https://www.instagram.com/kidcitystores/?hl=en" target="_blank"><i class="icon-instagram" aria-hidden="true"></i></a>
		<!--<a class="twitter-logo" href="#"></a>-->
		<a class="totop" href="#"></a>
	</div>
    <ul class="footer-payments-block">
        <li><span class="visa">Visa</span></li>
        <li><span class="paypal">PayPal</span></li>
        <li><span class="mastercard">Mastercard</span></li>
        <li><span class="discover">Discover</span></li>
        <li><span class="amExpress">AmericanExpress</span></li>
    </ul>
</div>
<!--<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script>-->
<!--<script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us5.list-manage.com","uuid":"e63d3ec47059b6abdf6a36c8f","lid":"c5c2780cae"}) })</script>-->
<!--BOF part/Layer -->
<div id="overlay">
    <div class="transBg"></div>
    <div class="pageContainer">
        <div class="close-pageLayer"><a class="close-layer" onclick="pageClose('#overlay');" aria-label="close">&times;</a></div>
        <div class="pageLayer">
            <div id="ajaxContent"></div>
        </div>
    </div>
</div>
<!--EOF part/Layer -->