<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Theme\Block\Html\Notices
 */
?>
<?php 
$els = explode('/',$_SERVER['REQUEST_URI']);
if(in_array('checkout',$els) && !in_array('cart',$els)){
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
if(!in_array('success',$els)){
$grandTotal = $cart->getQuote()->getGrandTotal();
}
else{
$session = $objectManager->create('\Magento\Checkout\Model\Session');
$order_s = $session->getLastRealOrder();	

$grandTotal = $order_s->getGrandTotal();	
    }
}
    if($_SERVER['REQUEST_URI'] == '/checkout/onepage/success/') :
?>
<!-- Google Code for Purchase Conversion Page -->

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 832600884;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "bUC3CKquwXUQtPaBjQM";
var google_conversion_value = <?= round($grandTotal,2); ?>;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/832600884/?value=<?= round($grandTotal,2); ?>&amp;currency_code=USD&amp;label=bUC3CKquwXUQtPaBjQM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<?php	
    endif;


if ($block->displayNoscriptNotice()): ?>
    <noscript>
        <div class="message global noscript">
            <div class="content">
                <p>
                    <strong><?php /* @escapeNotVerified */ echo __('JavaScript seems to be disabled in your browser.'); ?></strong>
                    <span><?php /* @escapeNotVerified */ echo __('For the best experience on our site, be sure to turn on Javascript in your browser.'); ?></span>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($block->displayNoLocalStorageNotice()): ?>
    <div class="notice global site local_storage" style="display: none;">
        <div class="content">
            <p>
                <strong><?php /* @escapeNotVerified */ echo __('Local Storage seems to be disabled in your browser.'); ?></strong><br />
                <?php /* @escapeNotVerified */ echo __('For the best experience on our site, be sure to turn on Local Storage in your browser.'); ?>
            </p>
        </div>
    </div>
    <script>
require(['jquery'], function(jQuery){

        // <![CDATA[
        (function($) {
            var test = 'test';
            try {
                localStorage.setItem(test, test);
                localStorage.removeItem(test);
            } catch(e) {
                $(".notice.global.site.local_storage").show();
            }
        })(jQuery);
        // ]]>

});
</script>
<?php endif; ?>
<?php if ($block->displayDemoNotice()): ?>
    <div class="message global demo">
        <div class="content">
            <p><?php /* @escapeNotVerified */ echo __('This is demo store. No orders will be fulfilled.') ?></p>
        </div>
    </div>
<?php endif; ?>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$orderDatamodel = $objectManager->get('Magento\Sales\Model\Order')->getCollection()->getLastItem();
$orderId   =   $orderDatamodel->getId();
$email = $orderDatamodel->getCustomerEmail();?>

<script>
    require(['jquery'], function(jQuery){

        // <![CDATA[
        if(window.location.pathname == '/checkout/onepage/success/'){
            var lastOrderId = <?php echo $orderId ?>;
            var email = '<?php echo $email ?>';

            var _cnx = _cnx || [];
            _cnx.push(['mid', 1000373]);
            _cnx.push(['surveyType', 'pos']);
            _cnx.push(['orderId', lastOrderId]);
            _cnx.push(['emailAddress', email]);
            (function (w, d, t) {
                var s = d.createElement(t);
                s.async = true;
                s.src = '//insights.bizrate.com/js/init.js';
                var h = d.getElementsByTagName(t)[0];
                h.parentNode.insertBefore(s, h);
            })(window, document, "script");

        }else if(window.location.pathname != '/checkout/onepage/success/'){

            var _cnx = _cnx || [];
            _cnx.push(['mid', 1000373]);
            (function (w, d, t) {
                var s = d.createElement(t);
                s.async = true;
                s.src = '//insights.bizrate.com/js/init.js';
                var h = d.getElementsByTagName(t)[0];
                h.parentNode.insertBefore(s, h);
            })(window, document, 'script');
        }
        // ]]>

    });
</script>
