<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Buy Now'); ?>
<?php if ($_product->isSaleable()): ?>

    
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="select-wrapper">
            <select class="product__select form-control"  id="qty" name="qty">
                            
                            <option value="1" selected>1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                          </select>
			
        </div>
        <?php endif; ?>
        
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action tocart product__btn"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>



<?php endif; ?>


<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
		'Abovebits_TopBanner/js/add-to-cart'
        //'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function($){	
		$('[data-block="minicart"]').bind('contentLoading', function(e, a){
			$(this).data('cart-content-load', 1);
		});		
		$('[data-block="minicart"]').bind('contentUpdated', function(e, a){
			var loadFlag = $(this).data('cart-content-load');	
			if (loadFlag == 1) {
				$('.mage-dropdown-dialog > .ui-dialog-content').dropdownDialog('open');
				$(this).data('cart-content-load', 0);
			}
		});		
    });
</script>