<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
<div class="content-container">
            <div class="share">
              <h3>Share Product</h3>
			  <a class='st_facebook_large' displayText='Facebook'></a><a class='st_instagram_large' displayText='Instagram'></a><a class='st_pinterest_large' displayText='Pinterest'></a><a class='st_twitter_large' displayText='Tweet'></a>
            </div>
          </div>
		  