<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?><?php

    
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
  
if ($exist):?>
<div class="content-container">
                    <div class="common-head">
                      <h2><?php echo __('You may also liked'); ?></h2>
                    </div>
    
   
   
        <div class="cat-carousel">
              <ul>
                
               
                <?php 
				$i=0;
				foreach ($items as $_item):  if($i==4) break; $i++;?>
               <li>
						<div class="cat-item test-3">
								  
								  <div class="cat-item__img--lowmargin-top"><a href="<?php  echo $_item->getProductUrl() ?>">
								  
								 <?php $productImage = $block->getImage($_item, 'category_page_list'); ?>
								 <?php $productImage->setTemplate('Magento_Catalog::product/image.phtml'); ?>
								 <?php echo $productImage->toHtml(); ?>
								  </a></div>
								  <div class="cat-item__name"><a href="<?php  echo $_item->getProductUrl() ?>"><?php echo $block->escapeHtml($_item->getName()) ?></a></div>
								  <a href="<?php  echo $_item->getProductUrl() ?>" class="shop-now-button"><?php echo __('Shop Now') ?></a>
								  
								<div class="cat-item__new"><?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
									$_item,
									\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
									\Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
									[
										'price_id_suffix' => '-' . $type
									]
								) ?></div>
						</div>
                    </li>
                    <?php endforeach ?>
                </ul>
        </div>
    </div>
<?php endif;?>
