<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>
<?php $swatchData = $block->getSwatchData(); ?>
<div class="swatch-attribute swatch-layered <?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>"
     attribute-code="<?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>" attribute-id="174">
    <div class="swatch-attribute-options clearfix test111">
		<?php $limit = 5; $i=0;?>
        <?php foreach ($swatchData['options'] as $option => $label): ?>
			<?php  
			if($label['custom_style']!='disabled') $i++;
			if($i>$limit) {$class="hideoption ";} else{$class="";} 
			?>
            <a href="<?php /* @escapeNotVerified */ echo $label['link'] ?>" class="<?= $class ?> swatch-option-link-layered">
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="swatch-option <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 option-type="3"
                                 option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                                ></div>
                            <?php    break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="<?= $class ?> swatch-option image <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 option-type="2"
                                 option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 option-tooltip-thumb="<?php /* @escapeNotVerified */ echo $swatchThumbPath ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?php /* @escapeNotVerified */ echo $swatchImagePath ?>) no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '1':
                            ?>
                            <div class="<?= $class ?> swatch-option color <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                 option-type="1"
                                 option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                 option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?>"
                                 style="background: <?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?> no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '0':
                        default:
                            ?>
                                <div class="swatch-option text <?php /* @escapeNotVerified */ echo $label['custom_style'] ?>"
                                     option-type="0"
                                     option-id="<?php /* @escapeNotVerified */ echo $option ?>"
                                     option-label="<?php /* @escapeNotVerified */ echo $label['label'] ?>"
                                     option-tooltip-thumb=""
                                     option-tooltip-value=""
                                    ><?php /* @escapeNotVerified */ echo $swatchData['swatches'][$option]['value'] ?></div>
                            <?php    break;
                    } ?>
                <?php } ?>
            </a>
        <?php endforeach; ?>
		<?php if($i>$limit){ ?>
		<div class="viewmore" onclick="jQuery('.swatch-attribute.<?php echo $swatchData['attribute_code'] ?> .hideoption ').css('display','inline');jQuery(this).hide();">Show more</div>
		<?php } ?>
    </div>
</div>

<script>
    require(["jquery", "jquery/ui", "swatchRenderer"], function ($) {
        $('.swatch-layered.<?php /* @escapeNotVerified */ echo $swatchData['attribute_code'] ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
