<?php
?>
<div id="contact-page-banner">
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-page-banner')->toHtml(); ?>
</div>
<div id="contact-form-page">
	<div class="width-50">
		<fieldset class="fieldset">
			<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('CUSTOMER SERVICE') ?></span></legend>
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-page-text')->toHtml(); ?>
		</fieldset>
	</div>
	<div class="width-50">
		<form class="form contact"
			  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
			  id="contact-form"
			  method="post"
			  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
			  data-mage-init='{"validation":{}}'>
			<fieldset class="fieldset">
				<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('GET IN TOUCH') ?></span></legend>
				<div class="field name required">
					<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?>:</span></label>
					<div class="control">
						<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
					</div>
				</div>
				<div class="field email required">
					<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?>:</span></label>
					<div class="control">
						<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
					</div>
				</div>
				<div class="field subject">
					<label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?>:</span></label>
					<div class="control">
						<input name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Subject') ?>" value="" class="input-text" type="text" />
					</div>
				</div>
				<div class="field comment required">
					<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Description') ?>:</span></label>
					<div class="control">
						<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Description') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
					</div>
				</div>
				<?php echo $block->getChildHtml('form.additional.info'); ?>
			</fieldset>
			<div id="reqinfo"><span><?php /* @escapeNotVerified */ echo __('Required') ?></span></div>
			<div class="actions-toolbar">
				<div class="primary">
					<input type="hidden" name="hideit" id="hideit" value="" />
					<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
						<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
					</button>
				</div>
			</div>
		</form>
	</div>
	<div class="clear"></div>
</div>