<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
$currentOrder_request = (isset($_REQUEST['product_list_order']) && $_REQUEST['product_list_order'] != '') ? $_REQUEST['product_list_order'] : '';
?>
<div class="toolbar-sorter sorter">
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
          <?php $selected = "";?>
              <?php
                if ($currentOrder_request == '' && $_key == 'created_at'):
                  $selected = ' selected="selected"';
                elseif ($currentOrder_request != '' && $block->isOrderCurrent($_key)):
                  $selected = ' selected="selected"';
                endif;
                ?>

            <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php echo $selected;?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>

</div>